# Generated by Django 4.1.5 on 2023-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'username', 'first_name', 'last_name'], name='api_user_id_c5291b_idx'),
        ),
    ]
